import:
    - https://www.nextzen.org/carto/refill-style/refill-style.zip
    - https://s3.amazonaws.com/xyz-demo/data/demo.yaml
    # - https://www.nextzen.org/carto/refill-style/11/themes/label-4.zip

sources:

    _satellite:
        # url: https://1.aerial.maps.api.here.com/maptile/2.1/maptile/newest/terrain.day/{z}/{x}/{y}/512/png
        url: https://1.aerial.maps.api.here.com/maptile/2.1/maptile/newest/satellite.day/{z}/{x}/{y}/512/png
        #url: https://services.digitalglobe.com/mapservice/wmtsaccess?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&LAYER=DigitalGlobe:ImageryTileService&featureProfile=Accuracy_Profile&FORMAT=image/png&STYLE=&CONNECTID=1b207260-1627-4a35-945e-089b8cf09f78&TileMatrixSet=EPSG:3857&TileMatrix=EPSG:3857:{z}&TileRow={y}&TileCol={x}
        type: Raster
        rasters: [terrain_normals]
        url_params:
            app_id: "KoA3V0dBQ1DDzcsJqjS0"
            app_code: "T3x1q-hvhyzZo3ZmxPVgYg"
    mapzen:
    # _here_osm:
        url: https://xyz.api.here.com/tiles/osmbase/256/all/{z}/{x}/{y}.mvt
        url_params:
            access_token: AVoxWfIDYgZOr4zOaUV3urg
        type: MVT
        max_zoom: 15

styles:

    # applying terrain lighting with normal map to raster
    # raster layer to light is raster 0, normal map is raster 1
    terrain_raster:
        base: raster
        lighting: false # don't use scene lighting, use custom lighting in shader
        shaders:
            uniforms:
                u_light: [-0.5, 0.5, -0.5] # lights are flipped to match sat hillshade
                u_ambient: 0.5
            blocks:
                filter: |
                    // simple directional light with Lambert shading
                    vec3 terrain = normalize(sampleRaster(1).xyz *2. - 1.4); // terrain surface normal
                    float diffuse = clamp(dot(terrain, normalize(-u_light)), 0., 1.);
                    color.rgb = clamp((color.rgb * u_ambient) + (color.rgb * diffuse), 0., 1.);

layers:
    water:
        enabled: false
    earth:
        enabled: false
    landuse:
        enabled: false
    buildings:
        enabled: false
        filter: function(){ return false } # set this to permanently turn off all buildings, since Invader  will re-enable layer
    roads:
        filter:
            not:
                kind: ferry
        # enabled: false
        # fake out road lines and just leave labels
        z:
            y:
                no_lines:
                    # enabled: false
                    # if no_lines is enabled, it will NOT draw road lines, just labels (inheritance overrides basemap default). uncomment  'enabled: false' if you *do* want road lines
                    draw:
                        lines:
                            width: 0px

    _satellite:
        enabled: false
        data: {source: _satellite}
        draw:
            raster:
                order: 0
    _satellite_shader:
        # slight enhancement of terrain with shaders and Nextzen terrain tiles
        # enabled: false
        data: {source: _satellite}
        draw:
            terrain_raster:
                order: 0

