/*
 *
 *   Copyright (C) 2017-2019 HERE Europe B.V.
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 *
 *   SPDX-License-Identifier: Apache-2.0
 *   License-Filename: LICENSE
 *
 *
 */

export const LOADING = 'LOADING';
export const LOADING_SCREEN = 'LOADING_SCREEN';
export const IFRAME_LOADER = 'IFRAME_LOADER';

export const TOGGLE_NOTIFICATION_BAR = 'TOGGLE_NOTIFICATION_BAR';

export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECT = 'FETCH_PROJECT';
export const NEW_PROJECT = 'NEW_PROJECT';
export const STAR_PROJECT = 'STAR_PROJECT';
export const RENAME_PROJECT = 'RENAME_PROJECT';
export const RESET_CURRENT_PROJECT = 'RESET_CURRENT_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const PUBLISH_PROJECT = 'PUBLISH_PROJECT';
export const SELECT_DEFAULT_BOOKMARK = 'SELECT_DEFAULT_BOOKMARK';
export const SELECT_DEFAULT_LICENSE = 'SELECT_DEFAULT_LICENSE';
export const DELETING_PROJECT = 'DELETING_PROJECT';
export const SET_PROJECT_THUMBNAIL = 'SET_PROJECT_THUMBNAIL';
export const SHOW_NAME = 'SHOW_NAME';
export const SHOW_DESCRIPTION = 'SHOW_DESCRIPTION';
export const ENABLE_CARDS = 'ENABLE_CARDS';
export const SHOW_LEGEND = 'SHOW_LEGEND';
export const SELECT_VIEWER = 'SELECT_VIEWER';

export const HIDE_LAYER = 'HIDE_LAYER';
export const RENAME_LAYER = 'RENAME_LAYER';
export const ADD_LAYERS = 'ADD_LAYERS';
export const DELETE_LAYER = 'DELETE_LAYER';
// export const UPDATE_OLD_PROJECT = 'UPDATE_OLD_PROJECT';
export const DELETE_LAYER_INTENT = 'DELETE_LAYER_INTENT';
export const EDIT_LAYER = 'EDIT_LAYER';
export const UPDATE_LAYER = 'UPDATE_LAYER';
export const UPDATE_LAST_SAVED_TIME = 'UPDATE_LAST_SAVED_TIME';
export const UPDATE_PROJECT_LAYERS = 'UPDATE_PROJECT_LAYERS';
export const UPDATE_PROJECT_NAME = 'UPDATE_PROJECT_NAME';
export const UPDATE_PROJECT_DESCRIPTION = 'UPDATE_PROJECT_DESCRIPTION';
export const UPDATE_LAYER_BBOX = 'UPDATE_LAYER_BBOX';
export const SORT_LAYER_CARD_ITEMS = 'SORT_LAYER_CARD_ITEMS';
export const CHANGE_BASE_TILELAYER = 'CHANGE_BASE_TILELAYER';
export const CHANGE_BASE_THEME = 'CHANGE_BASE_THEME';
export const CHANGE_BASE_VIEW = 'CHANGE_BASE_VIEW';
export const CHANGE_SHOW_LABELS = 'CHANGE_SHOW_LABELS';
export const UPDATE_MAP_SETTINGS = 'UPDATE_MAP_SETTINGS';
export const ADD_BOOKMARK = 'ADD_BOOKMARK';
export const CLICK_BOOKMARK = 'CLICK_BOOKMARK';
export const DELETE_BOOKMARK = 'DELETE_BOOKMARK';
export const TOGGLE_CARD_VISIBILITY = 'TOGGLE_CARD_VISIBILITY';
export const TOGGLE_TEXT_STYLE = 'TOGGLE_TEXT_STYLE';
export const TOGGLE_ICON_STYLE = 'TOGGLE_ICON_STYLE';
export const ADD_FEATURE_PROP = 'ADD_FEATURE_PROP';
export const DELETE_FEATURE_PROP = 'DELETE_FEATURE_PROP';
export const SET_CURRENT_FEATURE = 'SET_CURRENT_FEATURE';
export const SET_CURRENT_FEATURES = 'SET_CURRENT_FEATURES';
export const UPDATE_CURRENT_FEATURE = 'UPDATE_CURRENT_FEATURE';
export const UPDATING_FEATURE = 'UPDATING_FEATURE';
export const UPDATE_MAP_BBOX = 'UPDATE_MAP_BBOX';
export const SET_MAP_MODE = 'SET_MAP_MODE';
export const FILTER_WITH_EDIT_MODE = 'FILTER_WITH_EDIT_MODE';
export const UPDATE_GEOMETRIES_COUNT = 'UPDATE_GEOMETRIES_COUNT';
export const UPDATE_GEOMETRIES = 'UPDATE_GEOMETRIES';
export const UPDATE_GEOMETRY_VISIBILITY = 'UPDATE_GEOMETRY_VISIBILITY';
export const UPDATE_GEOMETRY_STYLEPROP = 'UPDATE_GEOMETRY_STYLEPROP';
export const ADD_COLOR_LOADER = 'ADD_COLOR_LOADER';
export const UPDATE_DEFAULT_STYLE_LABEL = 'UPDATE_DEFAULT_STYLE_LABEL';
export const PUBLISH_PROJECT_DASHBOARD = 'PUBLISH_PROJECT_DASHBOARD';
export const SELECT_DEFAULT_BOOKMARK_DASHBOARD =
  'SELECT_DEFAULT_BOOKMARK_DASHBOARD';
export const UPDATE_PROJECT_DISPLAY_SETTINGS =
  'UPDATE_PROJECT_DISPLAY_SETTINGS';
export const SELECT_VIEWER_DASHBOARD = 'SELECT_VIEWER_DASHBOARD';
export const UPDATE_OPEN_SPACE = 'UPDATE_OPEN_SPACE';
export const DELETE_TAG = 'DELETE_TAG';
export const SELECT_PUBLISH_ID = 'SELECT_PUBLISH_ID';
export const SELECT_PUBLISH_ID_FROM_DASHBOARD =
  'SELECT_PUBLISH_ID_FROM_DASHBOARD';
export const ADD_EMPTY_LAYER_HIGHLIGHT = 'ADD_EMPTY_LAYER_HIGHLIGHT';
export const REMOVE_EMPTY_LAYER_HIGHLIGHT = 'REMOVE_EMPTY_LAYER_HIGHLIGHT';
export const PROPERTY_FILTER_APPLIED = 'PROPERTY_FILTER_APPLIED';
export const PROJECT_PUBLISHED = 'PROJECT_PUBLISHED';
export const SCHEMA_APPLIED = 'SCHEMA_APPLIED';
export const UPDATE_HEXBIN = 'UPDATE_HEXBIN';
export const REMOVE_HEXBIN = 'REMOVE_HEXBIN';

export const FETCH_SPACES = 'FETCH_SPACES';
export const UPDATE_SPACES = 'UPDATE_SPACES';
export const NEW_SPACE = 'NEW_SPACE';
export const NEW_DATA_ADDED = 'NEW_DATA_ADDED';
export const DELETING_SPACE = 'DELETING_SPACE';
export const DELETE_SPACE = 'DELETE_SPACE';
export const UPLOAD_PROGRESS_SPACE = 'UPLOAD_PROGRESS_SPACE';
export const CLEAN_UP_SPACES = 'CLEAN_UP_SPACES';
export const PRO_FEATURE_MAP = 'PRO_FEATURE_MAP';
export const VIRTUAL_SPACE = 'VIRTUAL_SPACE';
export const UPDATE_VIRTUAL_SPACE = 'UPDATE_VIRTUAL_SPACE';
export const DATA_ADDED_ON_SPACE = 'DATA_ADDED_ON_SPACE';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const SWITCH_APP_ID = 'SWITCH_APP_ID';
export const ACCOUNT_ME = 'ACCOUNT_ME';
export const UPDATE_APPID = 'UPDATE_APPID';
export const TC_UPDATE = 'TC_UPDATE';

export const FILES_DROP_START = 'FILES_DROP_START';
export const FILES_DROP_FINISH = 'FILES_DROP_FINISH';

export const ADD_STYLE_RULE = 'ADD_STYLE_RULE';
export const DELETE_STYLE_RULE = 'DELETE_STYLE_RULE';
export const EDIT_STYLE_RULE = 'EDIT_STYLE_RULE';
export const SORT_STYLE_RULES = 'SORT_STYLE_RULES';
export const SORT_GEOMETRY = 'SORT_GEOMETRY';
export const OPEN_STYLE_GEOMETRY_PANEL = 'OPEN_STYLE_GEOMETRY_PANEL';
export const OPEN_STYLE_RULE_PANEL = 'OPEN_STYLE_RULE_PANEL';

export const GEOCODED_FEATURES_SUCCESS = 'GEOCODED_FEATURES_SUCCESS';

export const UPDATE_GIS_FEATURE = 'UPDATE_GIS_FEATURE';
